### ISSUE TITLE
@SuppressWarnings("all")

### ISSUE THREAD

**Issue by KSolovyev** [Define-break-continue/sem2_somegame#19]
Нужно убрать и давить только те инспекции, которые светят напрасно. На счет конкатенации строк - она работает через StringBuilder. Вот цитата из документации:
The Java language provides special support for the string concatenation operator ( + ), and for conversion of other objects to strings. String concatenation is implemented through the StringBuilder(or StringBuffer) class and its append method. String conversions are implemented through the method toString, defined by Object and inherited by all classes in Java. For additional information on string concatenation and conversion, see Gosling, Joy, and Steele, The Java Language Specification.
Так что инспекции, когда говорят вам заменить StringBuilder на сложение строк, не советуют дурного. Но вы можете подавить их и написать как вам больше нравится. Это уже вопрос читаемости, а не производительности. Чего уж точно не стоит делать, так это давить все инспекции.
З.Ы. На мой взгляд конкатенация выглядит красивше.

**Comment by bagrusss** [comment]
Эво оно как.
Убрал подавление всех инспекций.
