### ISSUE TITLE
Написать тесты с реальной базой

### ISSUE THREAD

**Issue by KSolovyev** [Define-break-continue/sem2_somegame#20]
Это интеграционный вид тестов, который спасает от огромного количества багла. Писать советую следующим образом:
Создать базовый класс TestsWithDB, в нем:
BeforeClass - создание тестовой базы
After - очистка всех таблиц
AfterClass  - удаление тестовой базы
В прочем, как писать - решать вам. Требования такие:
-Использование реальной базы
-Боевая база должна остаться нетронутой
-Каждый тест должен стартовать в одинаковых условиях, на чистых таблицах
-Не делать моков, заглушек, фейков для инструментов работы с базой.

**Comment by bagrusss** [comment]
Показал на РК=)
