### ISSUE TITLE
Перенести создание баз из конструкторов DAO.

### ISSUE THREAD

**Issue by KSolovyev** [Define-break-continue/sem2_somegame#21]
Вообще создание схем в DAO это некоторое нарушение абстракции. Ведь это объект доступа к данным и он должен делать примерно то, что делает раздел манипуляции данными языка SQL (DML). Т.е. работать с уже созданной схемой. Механизм создания баз должен быть отделен. Сейчас мне будет достаточно, если вы вынесите его в отдельный метод. 
В дополнение к этому, имя админа и его пароль должны читаться из файла с конфигурацией

**Comment by bagrusss** [comment]
Перенес в отдельные методы DAO. Админы хранятся в отдельном конфиге.
