### ISSUE TITLE
Миграции

### ISSUE THREAD

**Issue by KSolovyev** [Define-break-continue/sem2_somegame#22]
Делать их уже скорее всего поздно, но я хочу, чтобы вы продумали архитектуру и изложили ее здесь. Проблема, которую решает система миграций в том, что на "боевых" у вас есть данные, которые ни в коем случае нельзя потерять, а версия баз данных отстает, т.к. разработка всегда находится впереди.
Требования к системе миграций следующие:
-Схема базы должна быть версионированна.
-Сервер должен запускаться на пустых базах.
-Сервер должен запускаться на любой валидной версии базы, обновляя ее до последней
-Сервер не должен запускаться, если версия базы  больше версии кода.
-Сервер не должен запускаться, если во время обновления произошел сбой.
-После обновления все данные, присутствующие в базе и не являющиеся оъектом обновления, должны сохраниться
*-Сервер должен уметь накатывать обновления баз данных с "пропуском". Т.е пропускать ненужные или вредные в данной версии обновления. Естественно, позже, когда пропущенные куски потребуются, они должны накатится автоматически, если в процессе не возникнет ошибок.

**Comment by bagrusss** [comment]
O_o
Я бы хотел на РК рассказать, поскольку имеются вопросы.

**Comment by KSolovyev** [comment]
В субботу будет уже защита проектов, так что пиши вопросы текстом)

**Comment by bagrusss** [comment]
В базе данные есть служебная таблица, в которой хранится история миграций.
(Id, MajorVersion, MinorVersion, FileNumber, Comment, MigrationDate)
Текущая версия БД - запись в таблице с самой свежей датой.
Обязательно есть файл с первоначальной схемой БД.
Файл миграций содержит SQL запросы, которые обновляют схему. При применении файла миграции в талбицу истории добавляется новая запись.
Для выполнения автоматического обновления до новой версии необходимо получить запись из таблицы истории с текущей актуальной версий (по дате) и последовательно применить миграции из файлов, номера которых превышают текущую версию.

В Executor я бы добавил метод 
void makeMigrations(@Nullable List<String> files) thorw SQLException{
    if (files==null){
        miggrateToLast();//пройтись по файлам и примеить миграции.
    } else {
       for (String file : files){
           migrateFromFile(file);//принять конкретные миграции.
       }
    }
}
